import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { ENABLE_GOOGLE_GROUP_AUTO_CREATE, ENABLE_GOOGLE_GROUP_MEMBERSHIP_CHECK, GOOGLE_GROUP_DOMAIN, GOOGLE_GROUP_EMAIL_SUFFIX } from "@/lib/config";
import { generateGoogleGroupEmail } from "@/lib/google-groups";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { createRoleGroupGoogleGroupAction, createRoleGroupWelcomeTemplateAction, recheckRoleGroupMembershipsAction, resendAssignmentWelcomeAction, retryAssignmentGoogleSyncAction, saveRoleGroupGoogleSettingsAction, testRoleGroupGoogleGroupAction } from "@/app/projects/[projectId]/google-groups/actions";

export const dynamic = "force-dynamic";
function title(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default async function ProjectGoogleGroupsPage({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams?: Promise<{ error?: string; success?: string }> }) {
  const { projectId } = await params; const query = await searchParams; await requireUser(); const supabase = await createSupabaseServerClient();
  const [{ data: project }, { data: roles }, { data: settings }, { data: templates }, { data: assignments }, { data: logs }] = await Promise.all([
    supabase.from("projects").select("id, title, slug").eq("id", projectId).maybeSingle(),
    supabase.from("project_roles").select("id, name, role_group").eq("project_id", projectId).order("role_group").order("name"),
    supabase.from("project_role_group_google_settings").select("*").eq("project_id", projectId),
    supabase.from("email_templates").select("id, name, subject_template").or(`project_id.eq.${projectId},project_id.is.null`).eq("template_type", "role_group_welcome").eq("active", true).order("name"),
    supabase.from("role_assignments").select("id, role_id, person_id, google_group_sync_status, google_group_sync_error, google_group_membership_checked_at, welcome_email_status, welcome_email_error, project_roles(name, role_group), people(full_name, preferred_name, email)").eq("project_id", projectId).order("created_at"),
    supabase.from("google_group_action_log").select("id, role_group, action_type, status, email_address, active_google_group_email, error_message, created_at").eq("project_id", projectId).order("created_at", { ascending: false }).limit(100)
  ]);
  if (!project) notFound();
  const roleGroups = Array.from(new Set((roles ?? []).map((role) => String(role.role_group)))).sort(); const settingsByGroup = new Map((settings ?? []).map((row) => [String(row.role_group), row]));
  return <div className="page"><div className="page-header"><div><p className="eyebrow">{project.title}</p><h1>Google Groups</h1><p className="muted">Create each group in Google Admin, then connect its email here for automatic membership and welcome messages.</p></div><Link className="button secondary" href={`/projects/${projectId}`}>Back to project</Link></div>
    {query?.error?<p className="setup-warning">{query.error}</p>:null}{query?.success?<p className="setup-success">{query.success}</p>:null}
    <section className="panel"><div className="workspace-summary"><div><span>{ENABLE_GOOGLE_GROUP_MEMBERSHIP_CHECK?"On":"Off"}</span><p>Membership Checks</p></div><div><span>Manual</span><p>Group Changes</p></div><div><span>{GOOGLE_GROUP_EMAIL_SUFFIX||"None"}</span><p>Suggested Suffix</p></div><div><span>{GOOGLE_GROUP_DOMAIN}</span><p>Domain</p></div></div><p className="muted">Create and manage groups in Google. Production Management uses Apps Script to verify membership and flag missing people.</p>{!ENABLE_GOOGLE_GROUP_MEMBERSHIP_CHECK?<p className="setup-warning">Apps Script membership checking is not configured or enabled yet. Group addresses and welcome templates can still be prepared.</p>:null}</section>
    <div className="stacked-form">{roleGroups.map((group) => { const row = settingsByGroup.get(group); const proposed = generateGoogleGroupEmail(project.slug, group); const groupAssignments=(assignments??[]).filter((assignment)=>String((assignment.project_roles as unknown as {role_group:string}|null)?.role_group)===group); return <details className="integration-panel" key={group} open><summary><strong>{title(group)}</strong><span>{row?.active_google_group_email||proposed} · Creation: {row?.google_group_creation_status||"not attempted"} · Last sync: {row?.last_sync_status||"not attempted"}</span></summary>
      <form action={saveRoleGroupGoogleSettingsAction} className="stacked-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="roleGroup" value={group}/><div className="form-row"><label className="field"><span>Google Group mode</span><select name="googleGroupMode" defaultValue={row?.google_group_mode==="disabled"?"disabled":"manual"}><option value="manual">Manual existing group</option><option value="disabled">Disabled</option>{ENABLE_GOOGLE_GROUP_AUTO_CREATE?<option value="auto">Auto create (experimental)</option>:null}</select></label><label className="field"><span>Suggested Google Group email</span><input value={proposed} readOnly/></label></div><label className="field"><span>Actual Google Group email</span><input type="email" name="manualGoogleGroupEmail" defaultValue={row?.active_google_group_email??""} placeholder={proposed}/><small>Paste the complete email shown in Google after the group is created.</small></label><div className="choice-grid"><label className="checkbox-card"><input type="checkbox" name="googleGroupSyncEnabled" defaultChecked={Boolean(row?.google_group_sync_enabled)}/><span>Check assigned people against Google membership</span></label><label className="checkbox-card"><input type="checkbox" name="welcomeEmailEnabled" defaultChecked={Boolean(row?.welcome_email_enabled)}/><span>Send custom HTML welcome email</span></label><label className="checkbox-card"><input type="checkbox" name="removeOnUnassign" defaultChecked={Boolean(row?.remove_from_google_group_on_unassign)}/><span>Flag manual Google removal when unassigned</span></label></div><label className="field"><span>Welcome email template</span><select name="welcomeEmailTemplateId" defaultValue={row?.welcome_email_template_id??""}><option value="">No template</option>{(templates??[]).map((template)=><option key={template.id} value={template.id}>{template.name} · {template.subject_template}</option>)}</select></label><button type="submit">Save manual group connection</button></form>
      <div className="form-actions">{ENABLE_GOOGLE_GROUP_AUTO_CREATE?<form action={createRoleGroupGoogleGroupAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="roleGroup" value={group}/><button type="submit">Create Google Group</button></form>:null}<form action={testRoleGroupGoogleGroupAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="roleGroup" value={group}/><button className="button secondary" type="submit">Test Google Group Connection</button></form></div>
      {row?.google_group_creation_error||row?.last_sync_error?<p className="setup-warning">{row.google_group_creation_error||row.last_sync_error}</p>:null}
      <details><summary>Create a new HTML welcome template</summary><form action={createRoleGroupWelcomeTemplateAction} className="stacked-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="roleGroup" value={group}/><label className="field"><span>Subject</span><input name="subject" defaultValue={`Welcome to {{project_title}} · {{role_group}}`} required/></label><label className="field"><span>HTML body</span><textarea name="bodyHtml" rows={10} defaultValue={`<h1>Welcome, {{person_name}}!</h1>\n<p>You have been assigned as <strong>{{role_name}}</strong> for <strong>{{project_title}}</strong>.</p>\n<p>Production group: <a href="mailto:{{google_group_email}}">{{google_group_email}}</a></p>\n<h2>Next steps</h2>\n<ul><li>Review the production schedule.</li><li>Watch for messages from the production team.</li></ul>`} required/></label><small>Variables: person_name, project_title, role_name, role_group, google_group_email</small><button type="submit">Create and select template</button></form></details>
      <h3>Assigned people</h3>{groupAssignments.length?<div className="form-actions"><form action={recheckRoleGroupMembershipsAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="roleGroup" value={group}/><button type="submit">Check all memberships</button></form></div>:null}{(()=>{const missing=groupAssignments.filter((assignment)=>assignment.google_group_sync_status==="missing").map((assignment)=>String((assignment.people as unknown as {email:string}|null)?.email||"")).filter(Boolean);return missing.length?<label className="field"><span>Missing from Google Group — copy these addresses</span><textarea readOnly rows={Math.min(8,missing.length+1)} value={missing.join("\n")}/></label>:null;})()}<div className="compact-list">{groupAssignments.length?groupAssignments.map((assignment)=>{const person=assignment.people as unknown as {full_name:string;preferred_name:string;email:string}|null;const checked=assignment.google_group_membership_checked_at?new Date(assignment.google_group_membership_checked_at).toLocaleString():"not checked";return <div className="table-row" key={assignment.id}><div><strong>{person?.preferred_name||person?.full_name}</strong><span>{person?.email||"No email"} · Membership: {assignment.google_group_sync_status} · Checked: {checked} · Welcome: {assignment.welcome_email_status}</span>{assignment.google_group_sync_error||assignment.welcome_email_error?<small className="danger-text">{assignment.google_group_sync_error||assignment.welcome_email_error}</small>:null}</div><div className="form-actions"><form action={retryAssignmentGoogleSyncAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="assignmentId" value={assignment.id}/><button className="button secondary" type="submit">Check membership</button></form><form action={resendAssignmentWelcomeAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="assignmentId" value={assignment.id}/><button className="button secondary" type="submit">Resend welcome</button></form></div></div>}):<p className="muted">No people assigned in this role group.</p>}</div>
    </details>;})}</div>
    <section className="panel"><h2>Recent Google and Welcome Actions</h2><div className="compact-list">{(logs??[]).map((log)=><div className="table-row" key={log.id}><div><strong>{title(log.action_type)}</strong><span>{new Date(log.created_at).toLocaleString()} · {title(log.role_group)} · {log.email_address||log.active_google_group_email}</span>{log.error_message?<small className="danger-text">{log.error_message}</small>:null}</div><span className={`status-badge ${log.status==="failed"?"gold":""}`}>{log.status}</span></div>)}</div></section>
  </div>;
}
