import Link from "next/link";
import { notFound } from "next/navigation";
import { CommunicationComposer } from "@/components/communication-composer";
import { HtmlMessageEditor } from "@/components/html-message-editor";
import { ProjectContextSwitcher } from "@/components/project-context-switcher";
import { ProjectWorkspaceNav } from "@/components/project-workspace-nav";
import { EmptyState } from "@/components/ui/empty-state";
import { FeedbackBanner } from "@/components/ui/feedback-banner";
import { InlineHelp } from "@/components/ui/inline-help";
import { StatusBadge } from "@/components/ui/status-badge";
import { cancelCommunicationCampaignAction, createCommunicationTemplateAction, createRecognitionAction, sendCommunicationCampaignAction, sendCommunicationTestAction } from "@/app/projects/[projectId]/communications/actions";
import { requireUser } from "@/lib/auth";
import { communicationTypeLabel } from "@/lib/communications";
import { sanitizeRichText } from "@/lib/rich-text";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";
type Campaign = { id: string; name: string; message_type: string; audience_description: string; status: string; recipient_count: number; sent_count: number; failed_count: number; created_at: string; sent_at: string | null };
type Recipient = { id: string; display_name: string; to_email: string; role_name: string; role_group: string; subject: string; body: string; status: string; error_message: string };

export default async function CommunicationsPage({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams?: Promise<{ campaign?: string; error?: string; success?: string }> }) {
  await requireUser();
  const { projectId } = await params; const query = await searchParams; const supabase = await createSupabaseServerClient();
  const [{ data: project }, { data: templates }, { data: assignments }, { data: auditions }, { data: campaigns }, { data: accomplishments }] = await Promise.all([
    supabase.from("projects").select("id, title").eq("id", projectId).maybeSingle(),
    supabase.from("email_templates").select("id, name, template_type, usage_tags, subject_template, body_template").or(`project_id.eq.${projectId},project_id.is.null`).eq("active", true).overlaps("usage_tags", ["cast_announcement","crew_announcement","role_confirmation","audition_reminder","audition_callback","recognition","custom"]).order("name"),
    supabase.from("role_assignments").select("id, person_id, status, people(id, full_name, preferred_name, email), project_roles(id, name, role_group)").eq("project_id", projectId).not("status", "in", "(declined,withdrawn)").order("created_at"),
    supabase.from("audition_submissions").select("id, person_id, audition_status, people(id, full_name, preferred_name, email)").eq("project_id", projectId).not("status", "eq", "cancelled"),
    supabase.from("communication_campaigns").select("id, name, message_type, audience_description, status, recipient_count, sent_count, failed_count, created_at, sent_at").eq("project_id", projectId).order("created_at", { ascending: false }).limit(100),
    supabase.from("profile_accomplishments").select("id, person_id, accomplishment_type, title, issuer, awarded_on, visibility, notified_at, people(full_name, preferred_name)").eq("project_id", projectId).order("created_at", { ascending: false }),
  ]);
  if (!project) notFound();
  const assignmentRows = assignments ?? []; const auditionRows = auditions ?? [];
  const peopleMap = new Map<string, { id: string; name: string; email: string }>();
  for (const row of [...assignmentRows, ...auditionRows]) { const person = row.people as unknown as { id: string; full_name: string; preferred_name: string; email: string } | null; if (person) peopleMap.set(person.id, { id: person.id, name: person.preferred_name || person.full_name, email: person.email }); }
  const people = [...peopleMap.values()].sort((a,b)=>a.name.localeCompare(b.name));
  const roleGroups = [...new Set(assignmentRows.map((row) => String((row.project_roles as unknown as { role_group: string } | null)?.role_group || "")).filter(Boolean))].sort();
  const assignmentStatuses = [...new Set(assignmentRows.map((row) => String(row.status)).filter(Boolean))].sort();
  const auditionStatuses = [...new Set(auditionRows.map((row) => String(row.audition_status)).filter(Boolean))].sort();
  const selectedCampaign = (campaigns ?? []).find((item) => item.id === query?.campaign) as Campaign | undefined;
  let selectedRecipients: Recipient[] = [];
  if (selectedCampaign) { const { data } = await supabase.from("communication_recipients").select("id, display_name, to_email, role_name, role_group, subject, body, status, error_message").eq("campaign_id", selectedCampaign.id).order("display_name"); selectedRecipients = (data ?? []) as Recipient[]; }
  const campaignRows = (campaigns ?? []) as Campaign[];

  return <div className="page workspace-page">
    <div className="page-header"><div><p className="eyebrow">Communication & Recognition</p><h1>{project.title}</h1><p className="muted">Prepare individualized announcements, review every recipient, send safely, and preserve a durable recognition history.</p></div><div className="top-actions"><ProjectContextSwitcher projectId={projectId} workspace="communications"/><Link className="button secondary" href={`/projects/${projectId}/overview`}>Project</Link></div></div>
    <ProjectWorkspaceNav projectId={projectId} active="communications" />
    <FeedbackBanner error={query?.error} success={query?.success} />
    <InlineHelp title="Nothing sends while you are composing"><p>Generating a draft freezes the recipient list and creates an individualized preview for each person. You must review the draft and explicitly confirm before sending. A test sends only to the address you enter and does not mark any recipient as contacted.</p><p>Sent recipients are protected from duplicate delivery. If a campaign is partially successful, retry sends only to failed recipients.</p></InlineHelp>
    <nav className="workspace-nav" aria-label="Communication sections"><a href="#compose">Compose</a><a href="#templates">Templates</a><a href="#recognition">Recognition</a><a href="#history">History</a></nav>

    {selectedCampaign ? <section className="panel workspace-section campaign-review" id="review"><div className="section-heading"><div><p className="eyebrow">Review Before Sending</p><h2>{selectedCampaign.name}</h2><p className="muted">{communicationTypeLabel(selectedCampaign.message_type)} · {selectedCampaign.audience_description}</p></div><StatusBadge status={selectedCampaign.status}/></div>
      <div className="workspace-summary"><div><span>{selectedCampaign.recipient_count}</span><p>Recipients</p></div><div><span>{selectedCampaign.sent_count}</span><p>Sent</p></div><div><span>{selectedCampaign.failed_count}</span><p>Failed</p></div></div>
      {selectedRecipients[0] ? <div className="email-preview"><p className="eyebrow">Individualized preview</p><h3>{selectedRecipients[0].subject}</h3><p className="muted">To: {selectedRecipients[0].display_name} &lt;{selectedRecipients[0].to_email}&gt;</p><div className="rich-render" dangerouslySetInnerHTML={{ __html: sanitizeRichText(selectedRecipients[0].body) }} /></div> : null}
      <details className="integration-panel"><summary><strong>Review all {selectedRecipients.length} recipients</strong><span>Names, addresses, roles, delivery states, and errors</span></summary><div className="compact-list">{selectedRecipients.map((recipient)=><div className="table-row" key={recipient.id}><div><strong>{recipient.display_name}</strong><span>{recipient.to_email}{recipient.role_name ? ` · ${recipient.role_name}` : ""}</span>{recipient.error_message?<small className="danger-text">{recipient.error_message}</small>:null}</div><StatusBadge status={recipient.status}/></div>)}</div></details>
      {["draft","partial","sending"].includes(selectedCampaign.status) ? <div className="campaign-send-grid"><form action={sendCommunicationTestAction} className="stacked-form safe-test"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="campaignId" value={selectedCampaign.id}/><label className="field"><span>Safe test address</span><input type="email" name="testEmail" required placeholder="your-email@siena.edu"/></label><button className="button secondary" type="submit">Send test only</button></form><form action={sendCommunicationCampaignAction} className="stacked-form send-confirm"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="campaignId" value={selectedCampaign.id}/><label className="checkbox-card"><input type="checkbox" name="confirmSend" required/><span>I reviewed the message and all {selectedCampaign.status === "partial" ? selectedCampaign.failed_count : selectedCampaign.recipient_count} recipient{(selectedCampaign.status === "partial" ? selectedCampaign.failed_count : selectedCampaign.recipient_count) === 1 ? "" : "s"}.</span></label><button type="submit">{selectedCampaign.status === "partial" ? "Retry failed recipients only" : selectedCampaign.status === "sending" ? "Resume and reconcile delivery" : "Send campaign now"}</button></form><form action={cancelCommunicationCampaignAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="campaignId" value={selectedCampaign.id}/><button className="button danger" type="submit">Cancel unsent campaign</button></form></div> : null}
    </section> : null}

    <section className="panel workspace-section" id="compose"><div className="section-heading"><div><p className="eyebrow">Draft First</p><h2>Compose a campaign</h2><p className="muted">Choose a Siena starter or a saved project template, then select exactly who should receive it.</p></div></div><CommunicationComposer projectId={projectId} templates={templates ?? []} roleGroups={roleGroups} assignmentStatuses={assignmentStatuses} auditionStatuses={auditionStatuses} people={people}/></section>

    <section className="panel workspace-section" id="templates"><div className="section-heading"><div><p className="eyebrow">Reusable Copy</p><h2>Create an HTML template</h2><p className="muted">Saved project templates also appear in the central Email Templates module, where tags and wider availability can be managed.</p></div><Link className="button secondary" href="/settings/email-templates">Open template library</Link></div><details className="integration-panel"><summary><strong>New project template</strong><span>Headings, links, lists, and role-aware variables</span></summary><form action={createCommunicationTemplateAction} className="stacked-form"><input type="hidden" name="projectId" value={projectId}/><div className="form-row"><label className="field"><span>Template name</span><input name="name" required/></label><label className="field"><span>Message type</span><select name="messageType" defaultValue="custom">{["cast_announcement","crew_announcement","role_confirmation","audition_reminder","audition_callback","recognition","custom"].map((type)=><option value={type} key={type}>{communicationTypeLabel(type)}</option>)}</select></label></div><label className="field"><span>Subject template</span><input name="subject" required defaultValue="A message about {{project_title}}"/></label><HtmlMessageEditor name="bodyHtml" initialValue="<h3>Hello {{person_name}},</h3><p></p>" label="Template message"/><button type="submit">Save template</button></form></details></section>

    <section className="panel workspace-section" id="recognition"><div className="section-heading"><div><p className="eyebrow">Durable Person History</p><h2>Recognition & accomplishments</h2><p className="muted">Record the accomplishment once on the person’s profile and optionally prepare a private announcement draft.</p></div></div>
      <details className="integration-panel"><summary><strong>Add recognition</strong><span>ACTF, awards, milestones, certifications, and other accomplishments</span></summary><form action={createRecognitionAction} className="stacked-form"><input type="hidden" name="projectId" value={projectId}/><div className="form-row"><label className="field"><span>Person</span><select name="personId" required defaultValue=""><option value="">Choose person</option>{people.map((person)=><option value={person.id} key={person.id}>{person.name} · {person.email || "No email"}</option>)}</select></label><label className="field"><span>Type</span><select name="accomplishmentType" defaultValue="recognition"><option value="recognition">Recognition</option><option value="actf">ACTF</option><option value="award">Award</option><option value="milestone">Milestone</option><option value="certification">Certification</option><option value="achievement">Achievement</option></select></label></div><div className="form-row"><label className="field"><span>Title</span><input name="title" required/></label><label className="field"><span>Issuer</span><input name="issuer" defaultValue="Siena College"/></label><label className="field"><span>Date</span><input type="date" name="awardedOn"/></label></div><label className="field"><span>Description</span><textarea name="description" rows={4}/></label><div className="choice-grid"><label className="checkbox-card"><input type="radio" name="visibility" value="client_visible" defaultChecked/><span>Client visible — person can see this in their profile</span></label><label className="checkbox-card"><input type="radio" name="visibility" value="management_only"/><span>Management only — hidden from the person</span></label><label className="checkbox-card"><input type="checkbox" name="prepareAnnouncement"/><span>Prepare an individualized announcement draft for review</span></label></div><button type="submit">Save recognition</button></form></details>
      <div className="compact-list">{(accomplishments ?? []).length ? (accomplishments ?? []).map((item)=>{const person=item.people as unknown as {full_name:string;preferred_name:string}|null;return <div className="table-row" key={item.id}><div><strong>{item.title}</strong><span>{person?.preferred_name||person?.full_name} · {communicationTypeLabel(item.accomplishment_type)} · {item.issuer || "No issuer"}{item.awarded_on ? ` · ${new Date(`${item.awarded_on}T00:00:00Z`).toLocaleDateString("en-US", {timeZone:"UTC"})}` : ""}</span></div><div className="badge-row"><StatusBadge status={item.visibility === "client_visible" ? "published" : "disabled"} label={item.visibility === "client_visible" ? "Client visible" : "Management only"}/>{item.notified_at?<StatusBadge status="sent" label="Announcement sent"/>:null}</div></div>}) : <EmptyState title="No recognition recorded">Add an accomplishment above; it will remain with the person across productions.</EmptyState>}</div>
    </section>

    <section className="panel workspace-section" id="history"><div className="section-heading"><div><p className="eyebrow">Audit Trail</p><h2>Campaign history</h2><p className="muted">Drafts, deliveries, partial failures, and cancellations remain visible.</p></div></div><div className="compact-list">{campaignRows.length ? campaignRows.map((campaign)=><div className="table-row" key={campaign.id}><div><strong>{campaign.name}</strong><span>{communicationTypeLabel(campaign.message_type)} · {campaign.audience_description} · {new Date(campaign.created_at).toLocaleString("en-US")}</span></div><div className="form-actions"><StatusBadge status={campaign.status}/><Link className="button secondary" href={`/projects/${projectId}/communications?campaign=${campaign.id}`}>Open</Link></div></div>) : <EmptyState title="No campaigns yet">Generate your first review draft above. Nothing will send automatically.</EmptyState>}</div></section>
  </div>;
}
