"use client";

import { useEffect,useMemo,useState } from "react";
import { auditionDay as day, filterAuditionSlotChoices, type AuditionSlotChoice as Choice } from "@/lib/audition-slot-dependencies";

type Condition={field_key?:string;value?:string};

function selectedValues(name:string){return Array.from(document.getElementsByName(name)).flatMap((element)=>{const input=element as HTMLInputElement|HTMLSelectElement;if("checked" in input&&(input.type==="radio"||input.type==="checkbox"))return input.checked?[input.value]:[];return input.value?[input.value]:[];});}
export function AuditionSlotSelector({fieldKey,required,choices,sameDayAs,dependencyFilter="same_day",sessionMap={},condition}:{fieldKey:string;required:boolean;choices:Choice[];sameDayAs?:string;dependencyFilter?:"same_day"|"mapped_sessions";sessionMap?:Record<string,string[]>;condition?:Condition}){
  const [dependencyDay,setDependencyDay]=useState("");const [dependencySessionId,setDependencySessionId]=useState("");const [conditionValues,setConditionValues]=useState<string[]>([]);const [selected,setSelected]=useState("");
  useEffect(()=>{const names=[sameDayAs,condition?.field_key].filter(Boolean) as string[];const update=()=>{if(sameDayAs){const source=Array.from(document.getElementsByName(sameDayAs))[0] as HTMLSelectElement|undefined;const option=source?.selectedOptions[0];const nextDay=option?.dataset.day??"";const nextSessionId=option?.dataset.sessionId??"";setDependencyDay(nextDay);setDependencySessionId((current)=>{if(current!==nextSessionId)setSelected("");return nextSessionId;});}if(condition?.field_key)setConditionValues(selectedValues(condition.field_key));};update();for(const name of names)for(const element of Array.from(document.getElementsByName(name)))element.addEventListener("change",update);return()=>{for(const name of names)for(const element of Array.from(document.getElementsByName(name)))element.removeEventListener("change",update);};},[sameDayAs,condition?.field_key]);
  const active=!condition?.field_key||!condition.value||conditionValues.includes(condition.value);
  const filtered=useMemo(()=>filterAuditionSlotChoices(choices,dependencyFilter,dependencyDay,dependencySessionId,sessionMap),[choices,dependencyFilter,dependencyDay,dependencySessionId,sessionMap]);
  const waitingForLinkedBooking=Boolean(sameDayAs)&&!dependencySessionId;const locked=!active||waitingForLinkedBooking;
  return <div className={`audition-slot-control${locked?" is-locked":""}`}><select name={fieldKey} required={required&&!locked} disabled={locked} value={selected} onChange={(event)=>setSelected(event.target.value)} aria-disabled={locked}><option value="">{!active?"Complete the required question above first":waitingForLinkedBooking?"Choose the linked audition block first":"Choose an available time"}</option>{!locked?filtered.map((choice)=><option key={choice.id} value={choice.id} data-day={day(choice.startsAt)} data-session-id={choice.sessionId}>{choice.label}</option>):null}</select>{!active?<small>This audition booking will unlock when the required answer above is selected.</small>:null}{active&&waitingForLinkedBooking?<small>Choose the linked audition block first. Available times will then unlock and filter to the configured choices.</small>:null}{sameDayAs&&dependencySessionId&&!filtered.length?<p className="setup-warning">No mapped audition times remain for that selection. Contact production staff for an arrangement.</p>:null}</div>;
}
