"use client";

import { useId,useMemo,useState } from "react";

type Person={id:string;label:string;connected:boolean};
export function AuditionAccessInviteForm({projectId,people,action}:{projectId:string;people:Person[];action:(formData:FormData)=>void|Promise<void>}){
  const menuId=useId();const [personId,setPersonId]=useState("");const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const matches=useMemo(()=>{const search=query.trim().toLowerCase();return people.filter((person)=>!search||person.label.toLowerCase().includes(search)).slice(0,50);},[people,query]);
  return <form action={action} className="form-row"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="personId" value={personId}/><label className="field searchable-picker"><span>Choose staff person</span><input type="search" role="combobox" aria-controls={menuId} aria-expanded={open} value={query} placeholder="Search by name or email…" required onFocus={()=>setOpen(true)} onBlur={()=>window.setTimeout(()=>setOpen(false),120)} onChange={(event)=>{setQuery(event.target.value);setPersonId("");setOpen(true);}}/>{open?<div id={menuId} className="searchable-picker-menu" role="listbox">{matches.map((person)=><button type="button" role="option" aria-selected={person.id===personId} key={person.id} onMouseDown={(event)=>event.preventDefault()} onClick={()=>{setPersonId(person.id);setQuery(person.label);setOpen(false);}}>{person.label} · {person.connected?"access connected":"invitation required"}</button>)}{!matches.length?<span>No matching person profiles</span>:null}</div>:null}<small>People without connected access receive a branded one-time email. They do not register or create a password.</small></label><label className="field"><span>Project and audition access</span><select name="reviewerRole" defaultValue="production_manager"><option value="production_manager">Production manager · project manager and full audition access</option><option value="director">Director · project staff and full audition access</option><option value="intimacy_staff">Intimacy staff · project staff and restricted review</option></select></label><button type="submit" disabled={!personId}>Grant access or send invitation</button></form>;
}
