import { sanitizeRichText } from "@/lib/rich-text";
import type { OfferSection } from "@/lib/casting-offers";
import { commitmentGroupForSection, commitmentGroupForWindow, conflictWindowSummary, isMandatoryProductionCall, normalizedAvailability, shortTime, sortConflictWindows, type CommitmentGroup, type ConflictWindowAnswer, type ConflictWindowSnapshot, type OneOffConflict } from "@/lib/rehearsal-conflicts";

const labels:Record<CommitmentGroup,string>={rehearsal:"Rehearsals",tech:"Tech and dress",performance:"Performances and strike",other:"Other required calls"};

function Answer({window,answer}:{window:ConflictWindowSnapshot;answer:ConflictWindowAnswer}){
  const status=normalizedAvailability(answer.availability),mandatory=isMandatoryProductionCall(window);
  if(status==="fully_available")return <p>Fully Available{answer.unavailable_reason?` · ${answer.unavailable_reason}`:""}</p>;
  if(mandatory&&status==="partially_available")return <p><strong>Class conflict — student will notify the professor early and copy the production manager.</strong>{answer.unavailable_reason||answer.unavailable[0]?.reason?` · ${answer.unavailable_reason||answer.unavailable[0]?.reason}`:""}</p>;
  if(status==="unavailable")return <p><strong>{mandatory?"Unavailable — may affect casting":"Unavailable for the entire window"}</strong>{answer.unavailable_reason?` · ${answer.unavailable_reason}`:""}</p>;
  return <><p><strong>Partially Available — conflict times:</strong></p>{answer.unavailable.map((range,index)=><p key={index}>{shortTime(range.starts_at)}–{shortTime(range.ends_at)} · {range.reason}</p>)}</>;
}

export function ConflictResponseSummary({windows,answers,oneOff=[],generalNotes="",sections=[]}:{windows:ConflictWindowSnapshot[];answers:ConflictWindowAnswer[];oneOff?:OneOffConflict[];generalNotes?:string;sections?:OfferSection[]}){
  const byId=new Map(windows.map(window=>[window.id,window])),groups:CommitmentGroup[]=["rehearsal","tech","performance","other"];
  return <div className="conflict-response-summary">{groups.map(group=>{const rows=sortConflictWindows(windows).filter(window=>commitmentGroupForWindow(window)===group),agreements=sections.filter(section=>commitmentGroupForSection(section)===group);if(!rows.length&&!agreements.length)return null;return <section className="commitment-response-block receipt-block" key={group}><h2>{labels[group]}</h2><div className="compact-list">{rows.map(window=>{const answer=answers.find(item=>item.window_id===window.id);if(!answer)return null;return <div className="compact-row" key={window.id}><div><strong>{window.label}</strong><span>{conflictWindowSummary(window)}</span></div><div><Answer window={window} answer={answer}/>{answer.preference_enabled?<p><strong>Preference:</strong> {shortTime(answer.preference_start)}–{shortTime(answer.preference_end)}{answer.preference_notes?` · ${answer.preference_notes}`:""}</p>:null}</div></div>})}</div>{group==="rehearsal"&&oneOff.length?<><h3>Specific one-off rehearsal conflicts</h3><div className="compact-list">{oneOff.map((item,index)=>{const window=byId.get(item.window_id);return <div className="compact-row" key={`${item.window_id}-${item.occurrence_date}-${index}`}><div><strong>{new Intl.DateTimeFormat("en-US",{dateStyle:"full",timeZone:"UTC"}).format(new Date(`${item.occurrence_date}T12:00:00Z`))}</strong><span>{window?.label??"Rehearsal"}</span></div><p>{item.availability==="unavailable"?"Unavailable for the entire rehearsal":`Conflict: ${item.unavailable.map(range=>`${shortTime(range.starts_at)}–${shortTime(range.ends_at)}`).join(", ")}`} · {item.unavailable_reason}</p></div>})}</div></>:null}{agreements.map(section=><div className="commitment-agreement" key={section.key}><h3>{section.title}</h3><div className="rich-render" dangerouslySetInnerHTML={{__html:sanitizeRichText(section.body)}}/>{section.requires_response?<p className="agreement-receipt"><strong>✓ Acknowledged:</strong> <span className="rich-render" dangerouslySetInnerHTML={{__html:sanitizeRichText(section.acknowledgement)}}/></p>:null}</div>)}</section>})}{generalNotes?<><h3>Additional notes</h3><p style={{whiteSpace:"pre-wrap"}}>{generalNotes}</p></>:null}</div>;
}
