"use client";

import { useMemo, useState } from "react";
import { conflictOccurrences, conflictWindowSummary, sortConflictWindows, type ConflictCalendarSnapshot, type ConflictWindowAnswer, type ConflictWindowSnapshot, type OneOffConflict } from "@/lib/rehearsal-conflicts";

function blank(windowId:string):ConflictWindowAnswer{return{window_id:windowId,availability:"",unavailable_reason:"",unavailable:[{starts_at:"",ends_at:"",reason:""}],preference_enabled:false,preference_start:"",preference_end:"",preference_notes:""};}
function blankOneOff(key:string,windows:ConflictWindowSnapshot[]):OneOffConflict{const[windowId,date]=key.split(":");const window=windows.find(item=>item.id===windowId);return{window_id:windowId,occurrence_date:date,availability:"unavailable",unavailable_reason:"",unavailable:[{starts_at:window?.starts_at.slice(0,5)??"",ends_at:window?.ends_at.slice(0,5)??"",reason:""}]};}

export function ConflictResponseEditor({windows,calendar,name="conflictResponses",oneOffName="oneOffConflicts",initialAnswers=[],initialOneOff=[]}:{windows:ConflictWindowSnapshot[];calendar?:ConflictCalendarSnapshot;name?:string;oneOffName?:string;initialAnswers?:ConflictWindowAnswer[];initialOneOff?:OneOffConflict[]}){
  const ordered=useMemo(()=>sortConflictWindows(windows),[windows]);
  const occurrences=useMemo(()=>conflictOccurrences(ordered,calendar??null),[ordered,calendar]);
  const[answers,setAnswers]=useState<Record<string,ConflictWindowAnswer>>(()=>Object.fromEntries(ordered.map(window=>[window.id,initialAnswers.find(answer=>answer.window_id===window.id)??blank(window.id)])));
  const[oneOff,setOneOff]=useState<OneOffConflict[]>(initialOneOff);const[selectedOccurrence,setSelectedOccurrence]=useState("");
  const serialized=useMemo(()=>JSON.stringify(Object.values(answers).filter(answer=>answer.availability).map(answer=>({...answer,unavailable:answer.availability==="partially_available"?answer.unavailable:[]}))),[answers]);
  const oneOffSerialized=useMemo(()=>JSON.stringify(oneOff.map(item=>({...item,unavailable:item.availability==="partially_available"?item.unavailable.map(range=>({...range,reason:item.unavailable_reason})):[]}))),[oneOff]);
  const update=(id:string,change:Partial<ConflictWindowAnswer>)=>setAnswers(current=>({...current,[id]:{...current[id],...change}}));
  const addOneOff=()=>{if(!selectedOccurrence||oneOff.some(item=>`${item.window_id}:${item.occurrence_date}`===selectedOccurrence))return;setOneOff(current=>[...current,blankOneOff(selectedOccurrence,ordered)]);setSelectedOccurrence("");};
  return <section className="conflict-response-section">
    <input type="hidden" name={name} value={serialized}/><input type="hidden" name={oneOffName} value={oneOffSerialized}/>
    <div><h3>Production schedule availability</h3><p className="muted">Review every recurring rehearsal and dated production call. Tell us whether you are fully available, partially available, or unavailable. When entering times, list the times you <strong>cannot attend</strong>—not the times you are free.</p></div>
    <div className="conflict-window-stack">{ordered.map(window=>{const answer=answers[window.id];return <fieldset className="conflict-window-card" key={window.id}>
      <legend>{window.label}{window.required?" *":""}</legend><p><strong>{conflictWindowSummary(window)}</strong><br/><span className="muted">{window.call_type==="fixed"?"Scheduled rehearsal call":"Flexible rehearsal window"}{window.instructions?` · ${window.instructions}`:""}</span></p>
      <label className="field"><span>My availability</span><select required={window.required} value={answer.availability} onChange={event=>update(window.id,{availability:event.target.value as ConflictWindowAnswer["availability"]})}><option value="">Choose one</option><option value="fully_available">Fully available</option><option value="partially_available">Partially available</option><option value="unavailable">Unavailable for the entire window</option></select></label>
      {answer.availability==="partially_available"?<div className="conflict-ranges"><h4>Times I cannot attend</h4><p className="muted">Enter only your conflict times. For example, if you can rehearse after 7 PM, enter the conflict ending at 7 PM.</p>{answer.unavailable.map((interval,index)=><div className="conflict-range-row" key={index}>
        <label className="field"><span>Conflict begins</span><input type="time" required min={window.starts_at.slice(0,5)} max={window.ends_at.slice(0,5)} value={interval.starts_at} onChange={event=>update(window.id,{unavailable:answer.unavailable.map((item,i)=>i===index?{...item,starts_at:event.target.value}:item)})}/></label>
        <label className="field"><span>Conflict ends</span><input type="time" required min={window.starts_at.slice(0,5)} max={window.ends_at.slice(0,5)} value={interval.ends_at} onChange={event=>update(window.id,{unavailable:answer.unavailable.map((item,i)=>i===index?{...item,ends_at:event.target.value}:item)})}/></label>
        <label className="field conflict-reason"><span>Why are you unavailable? *</span><input required maxLength={500} value={interval.reason} onChange={event=>update(window.id,{unavailable:answer.unavailable.map((item,i)=>i===index?{...item,reason:event.target.value}:item)})}/></label>
        {answer.unavailable.length>1?<button className="secondary compact-button" type="button" onClick={()=>update(window.id,{unavailable:answer.unavailable.filter((_,i)=>i!==index)})}>Remove</button>:null}
      </div>)}<button className="secondary" type="button" onClick={()=>update(window.id,{unavailable:[...answer.unavailable,{starts_at:"",ends_at:"",reason:""}]})}>Add another conflict time</button></div>:null}
      {answer.availability==="unavailable"?<label className="field"><span>Why are you unavailable? *</span><textarea required rows={2} maxLength={500} value={answer.unavailable_reason} onChange={event=>update(window.id,{unavailable_reason:event.target.value})}/></label>:null}
      {window.collect_preferences?<div className="conflict-preference"><label className="check-row"><input type="checkbox" checked={answer.preference_enabled} onChange={event=>update(window.id,{preference_enabled:event.target.checked})}/><span>I have a preferred rehearsal time within this window</span></label>{answer.preference_enabled?<div className="conflict-range-row"><label className="field"><span>Prefer from</span><input type="time" required min={window.starts_at.slice(0,5)} max={window.ends_at.slice(0,5)} value={answer.preference_start} onChange={event=>update(window.id,{preference_start:event.target.value})}/></label><label className="field"><span>Until</span><input type="time" required min={window.starts_at.slice(0,5)} max={window.ends_at.slice(0,5)} value={answer.preference_end} onChange={event=>update(window.id,{preference_end:event.target.value})}/></label><label className="field conflict-reason"><span>Preference note (optional)</span><input maxLength={1000} value={answer.preference_notes} onChange={event=>update(window.id,{preference_notes:event.target.value})}/></label></div>:null}</div>:null}
    </fieldset>})}</div>
    {calendar&&occurrences.length?<section className="conflict-one-off"><h3>Specific one-off conflicts</h3><p className="muted">Add class trips, appointments, or other exceptions that affect one particular rehearsal. Holidays and blocked dates are not offered.</p><div className="form-row"><label className="field"><span>Choose the affected rehearsal</span><select value={selectedOccurrence} onChange={event=>setSelectedOccurrence(event.target.value)}><option value="">Choose a date and rehearsal</option>{occurrences.filter(item=>!oneOff.some(saved=>`${saved.window_id}:${saved.occurrence_date}`===item.key)).map(item=><option key={item.key} value={item.key}>{new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${item.date}T12:00:00Z`))} · {item.window.label} · {item.window.starts_at.slice(0,5)}–{item.window.ends_at.slice(0,5)}</option>)}</select></label><button type="button" className="secondary" onClick={addOneOff} disabled={!selectedOccurrence}>Add one-off conflict</button></div>
      <div className="conflict-window-stack">{oneOff.map((item,index)=>{const window=ordered.find(row=>row.id===item.window_id)!;return <fieldset className="conflict-window-card" key={`${item.window_id}:${item.occurrence_date}`}><legend>{new Intl.DateTimeFormat("en-US",{dateStyle:"full",timeZone:"UTC"}).format(new Date(`${item.occurrence_date}T12:00:00Z`))}</legend><p><strong>{window.label} · {window.starts_at.slice(0,5)}–{window.ends_at.slice(0,5)}</strong></p><label className="field"><span>Conflict type</span><select value={item.availability} onChange={event=>setOneOff(current=>current.map((row,i)=>i===index?{...row,availability:event.target.value as OneOffConflict["availability"]}:row))}><option value="unavailable">Unavailable for the entire rehearsal</option><option value="partially_available">Partially available</option></select></label><label className="field"><span>Why are you unavailable? *</span><input required maxLength={500} value={item.unavailable_reason} onChange={event=>setOneOff(current=>current.map((row,i)=>i===index?{...row,unavailable_reason:event.target.value,unavailable:row.unavailable.map(part=>({...part,reason:event.target.value}))}:row))}/></label>{item.availability==="partially_available"?<div className="conflict-range-row"><label className="field"><span>Conflict begins</span><input required type="time" min={window.starts_at.slice(0,5)} max={window.ends_at.slice(0,5)} value={item.unavailable[0]?.starts_at??""} onChange={event=>setOneOff(current=>current.map((row,i)=>i===index?{...row,unavailable:[{...row.unavailable[0],starts_at:event.target.value}]}:row))}/></label><label className="field"><span>Conflict ends</span><input required type="time" min={window.starts_at.slice(0,5)} max={window.ends_at.slice(0,5)} value={item.unavailable[0]?.ends_at??""} onChange={event=>setOneOff(current=>current.map((row,i)=>i===index?{...row,unavailable:[{...row.unavailable[0],ends_at:event.target.value}]}:row))}/></label></div>:null}<button type="button" className="secondary" onClick={()=>setOneOff(current=>current.filter((_,i)=>i!==index))}>Remove one-off conflict</button></fieldset>})}</div>
    </section>:calendar?<p className="muted">No dated rehearsal choices fall inside the configured rehearsal period.</p>:null}
  </section>;
}
