"use client";

import { useMemo,useState } from "react";
import { sendEmailTemplateTestAction } from "@/app/settings/email-templates/test-actions";
import { sanitizeRichText } from "@/lib/rich-text";
import { formatRoleGroupWelcomeEmail } from "@/lib/role-group-welcome-email";
import { formatPublicityReminderEmail } from "@/lib/publicity-reminder-email";

type Template={id:string;name:string;subject_template:string;body_template:string;usage_tags:string[]};
type Project={id:string;title:string;bioDue:string;headshotDue:string};
type Group={projectId:string;roleGroup:string;email:string;proparedLink:string};
function escape(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function render(value:string,variables:Record<string,string>){return value.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g,(_,key)=>variables[key]??`{{${key}}}`);}
export function EmailTemplatePreviewDrawer({templates,projects,groups,siteUrl}:{templates:Template[];projects:Project[];groups:Group[];siteUrl:string}){
  const [open,setOpen]=useState(false),[templateId,setTemplateId]=useState(templates[0]?.id??""),[projectId,setProjectId]=useState(projects[0]?.id??""),[personName,setPersonName]=useState("Mike Example"),[roleName,setRoleName]=useState("Production Team Member"),[roleGroup,setRoleGroup]=useState("production_team");const template=templates.find((item)=>item.id===templateId)??templates[0];const project=projects.find((item)=>item.id===projectId);const group=groups.find((item)=>item.projectId===projectId&&item.roleGroup===roleGroup);const base=siteUrl.replace(/\/+$/,""),variables=useMemo(()=>({person_name:escape(personName),full_name:escape(personName),preferred_name:escape(personName.split(" ")[0]||personName),project_title:escape(project?.title??"Sample Production"),role_name:escape(roleName),role_group:escape(roleGroup.replace(/_/g," ")),google_group_email:escape(group?.email||"sample-production-group@siena.edu"),propared_rolegroup_link:group?.proparedLink||base,profile_access_url:`${base}/profile-access`,role_acceptance_url:base,callback_response_url:`${base}/callbacks/00000000-0000-0000-0000-000000000000`,expires_in:"7 days",agreement_type:"cast",attendance_policy:"Attendance policy: Three unexcused absences may result in removal from the production. Each unexcused late arrival counts as one unexcused absence.",verification_code:"123456",outstanding_items:"show-specific bio, headshot, your approval",bio_due_date:project?.bioDue||"Not set",headshot_due_date:project?.headshotDue||"Not set",recognition_title:"Sample Recognition",recognition_issuer:"Siena Theatre",recognition_date:new Date().toLocaleDateString("en-US"),recognition_description:"A sample recognition description."}),[personName,project,roleName,roleGroup,group,base]);const subject=template?render(template.subject_template,variables):"";const rendered=template?sanitizeRichText(render(template.body_template,variables)):"";const html=template?.usage_tags.includes("role_group_welcome")?formatRoleGroupWelcomeEmail({bodyHtml:rendered,templateSource:template.body_template,projectTitle:project?.title??"Sample Production",roleGroup,profileAccessUrl:variables.profile_access_url}):rendered;
  const emailHtml=template?.usage_tags.includes("publicity_reminder")?formatPublicityReminderEmail({bodyHtml:rendered,templateSource:template.body_template,projectTitle:project?.title??"Sample Production",profileAccessUrl:variables.profile_access_url,outstandingItems:["show-specific bio","headshot","your approval"]}):html;
  return <><button type="button" onClick={()=>setOpen(true)}>Preview & test templates</button>{open?<div className="drawer-backdrop template-preview-backdrop" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target)setOpen(false);}}><aside className="template-preview-drawer" role="dialog" aria-modal="true" aria-label="Email template preview"><header className="drawer-header"><div><p className="eyebrow">Safe Preview</p><h2>Email template test</h2></div><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Close</button></header><div className="template-preview-controls"><label className="field"><span>Template</span><select value={templateId} onChange={(event)=>setTemplateId(event.target.value)}>{templates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Project</span><select value={projectId} onChange={(event)=>setProjectId(event.target.value)}><option value="">Sample production</option>{projects.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="form-row"><label className="field"><span>Preview person</span><input value={personName} onChange={(event)=>setPersonName(event.target.value)}/></label><label className="field"><span>Preview role</span><input value={roleName} onChange={(event)=>setRoleName(event.target.value)}/></label></div><label className="field"><span>Role group</span><select value={roleGroup} onChange={(event)=>setRoleGroup(event.target.value)}>{[...new Set(["cast","creative_team","directorial_team","production_team",...groups.filter((item)=>!projectId||item.projectId===projectId).map((item)=>item.roleGroup)])].map((item)=><option value={item} key={item}>{item.replace(/_/g," ")}</option>)}</select></label></div><section className="email-preview template-rendered-preview"><p className="eyebrow">Rendered email</p><h3>{subject}</h3><p className="muted">Tags filled using the sample context above.</p><div className="rich-render" dangerouslySetInnerHTML={{__html:emailHtml}}/></section><form action={sendEmailTemplateTestAction} className="stacked-form template-test-form"><input type="hidden" name="templateId" value={template?.id??""}/><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="personName" value={personName}/><input type="hidden" name="roleName" value={roleName}/><input type="hidden" name="roleGroup" value={roleGroup}/><label className="field"><span>Send this preview only to</span><input type="email" name="testEmail" required placeholder="your-email@siena.edu"/></label><p className="muted">Test links are safe substitutes. This does not create an invitation, code, reminder, campaign recipient, or onboarding change.</p><button type="submit">Send safe test email</button></form></aside></div>:null}</>;
}
