"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createStandardConflictWindowsAction, saveConflictCalendarAction, saveConflictWindowAction, setConflictWindowActiveAction } from "@/app/projects/[projectId]/conflicts/actions";
import { conflictDays, conflictWindowSummary, sortConflictWindows, type ConflictCalendarSnapshot, type ConflictWindowSnapshot } from "@/lib/rehearsal-conflicts";

type WindowRow=ConflictWindowSnapshot&{active:boolean};
export function RehearsalConflictsWorkspace({projectId,windows,calendar,canManage}:{projectId:string;windows:WindowRow[];calendar:ConflictCalendarSnapshot;canManage:boolean}){
  const router=useRouter();const[pending,startTransition]=useTransition();const[selected,setSelected]=useState<WindowRow|"new"|null>(null);const[message,setMessage]=useState<{error?:string;success?:string}>({});
  const current=selected&&selected!=="new"?selected:null;
  const run=(action:(data:FormData)=>Promise<{error?:string;success?:string}>,data:FormData,close=false)=>startTransition(async()=>{try{const result=await action(data);setMessage(result);if(result.success){if(close)setSelected(null);router.refresh();}}catch{setMessage({error:"The change could not be confirmed. Reload before trying again."});}});
  return <><section className="panel"><div className="section-heading"><div><p className="eyebrow">Configuration</p><h2>Rehearsal period</h2><p>This creates the dated choices used for one-off conflicts. Block holidays and other dates when rehearsal will not occur.</p></div></div>{canManage?<form className="stacked-form" action={(data)=>run(saveConflictCalendarAction,data)}><input type="hidden" name="projectId" value={projectId}/><div className="form-row"><label className="field"><span>First possible rehearsal date</span><input type="date" name="startsOn" required defaultValue={calendar?.starts_on??""}/></label><label className="field"><span>Last rehearsal date</span><input type="date" name="endsOn" required defaultValue={calendar?.ends_on??""}/></label></div><label className="field"><span>Blocked dates</span><textarea name="excludedDates" rows={3} defaultValue={(calendar?.excluded_dates??[]).join("\n")} placeholder={"2026-10-12\n2026-11-03"}/><small>Enter one holiday or no-rehearsal date per line. These dates will not appear in the actor’s one-off conflict picker.</small></label><button disabled={pending}>{pending?"Saving…":"Save rehearsal period"}</button></form>:calendar?<p>{calendar.starts_on} through {calendar.ends_on} · {(calendar.excluded_dates??[]).length} blocked date(s)</p>:<p className="empty-state">No dated rehearsal period configured.</p>}</section><section className="panel"><div className="section-heading"><div><p className="eyebrow">Configuration</p><h2>Availability windows</h2><p>Fixed calls collect conflicts. Flexible windows can also collect preferred times and a maximum call length.</p></div>{canManage?<button onClick={()=>{setSelected("new");setMessage({});}} type="button">Add window</button>:null}</div>
    {message.error?<p className="setup-warning" role="alert">{message.error}</p>:null}{message.success?<p className="setup-success" role="status">{message.success}</p>:null}
    {canManage&&!windows.some((window)=>window.active)?<form action={(data)=>run(createStandardConflictWindowsAction,data)}><input type="hidden" name="projectId" value={projectId}/><button className="secondary" disabled={pending}>Add standard Siena week</button><p className="muted">Monday–Thursday 6–10 PM fixed calls plus Sunday 10 AM–6 PM with a four-hour maximum and optional preferences.</p></form>:null}
    <div className="compact-list">{sortConflictWindows(windows).map((window)=><div className="compact-row" key={window.id}><div><strong>{window.label}</strong><span>{conflictWindowSummary(window)} · {window.applies_to} · {window.required?"required":"optional"}{!window.active?" · archived":""}</span></div>{canManage?<div className="top-actions"><button className="secondary" type="button" onClick={()=>{setSelected(window);setMessage({});}}>Edit</button><form action={(data)=>run(setConflictWindowActiveAction,data)}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="id" value={window.id}/><input type="hidden" name="active" value={String(!window.active)}/><button className="secondary" disabled={pending}>{window.active?"Archive":"Restore"}</button></form></div>:null}</div>)}{!windows.length?<p className="empty-state">No rehearsal availability windows are configured.</p>:null}</div>
    {selected?<form className="conflict-window-editor stacked-form" action={(data)=>run(saveConflictWindowAction,data,true)}><input type="hidden" name="projectId" value={projectId}/>{current?<input type="hidden" name="id" value={current.id}/>:null}<h3>{current?"Edit availability window":"Add availability window"}</h3>
      <label className="field"><span>Label *</span><input name="label" required maxLength={160} defaultValue={current?.label??""} placeholder="Sunday rehearsal window"/></label>
      <div className="form-row"><label className="field"><span>Schedule type</span><select name="recurrenceType" defaultValue={current?.recurrence_type??"weekly"}><option value="weekly">Repeats weekly</option><option value="date">Specific date</option></select></label><label className="field"><span>Weekday</span><select name="dayOfWeek" defaultValue={current?.day_of_week??0}>{conflictDays.map((day,index)=><option value={index} key={day}>{day}</option>)}</select><small>For a specific date, also choose the date below.</small></label><label className="field"><span>Specific date</span><input type="date" name="eventDate" defaultValue={current?.event_date??""}/></label></div>
      <div className="form-row"><label className="field"><span>Window starts *</span><input type="time" name="startsAt" required defaultValue={current?.starts_at.slice(0,5)??"18:00"}/></label><label className="field"><span>Window ends *</span><input type="time" name="endsAt" required defaultValue={current?.ends_at.slice(0,5)??"22:00"}/></label><label className="field"><span>Call type</span><select name="callType" defaultValue={current?.call_type??"fixed"}><option value="fixed">Fixed call</option><option value="flexible">Flexible within window</option></select></label><label className="field"><span>Maximum call minutes</span><input type="number" name="maxCallMinutes" min={15} max={720} step={15} defaultValue={current?.max_call_minutes??240}/><small>Used only for flexible calls.</small></label></div>
      <div className="form-row"><label className="field"><span>Applies to</span><select name="appliesTo" defaultValue={current?.applies_to??"cast"}><option value="cast">Cast</option><option value="crew">Crew</option><option value="all">Cast and crew</option></select></label><label className="check-row"><input type="checkbox" name="required" defaultChecked={current?.required??true}/><span>Response required</span></label><label className="check-row"><input type="checkbox" name="collectPreferences" defaultChecked={current?.collect_preferences??false}/><span>Collect optional preferred time</span></label></div>
      <label className="field"><span>Instructions</span><textarea name="instructions" rows={3} maxLength={2000} defaultValue={current?.instructions??""}/></label><div className="top-actions"><button disabled={pending}>{pending?"Saving…":"Save window"}</button><button className="secondary" type="button" disabled={pending} onClick={()=>setSelected(null)}>Cancel</button></div>
    </form>:null}
  </section></>;
}
