import { DISABLE_OUTBOUND_EMAIL,ENABLE_BUDGET_WRITES,ENABLE_GOOGLE_GROUP_MEMBERSHIP_CHECK,ENABLE_PLAYBILL_WRITES } from "@/lib/config";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export type ReadinessState="ready"|"attention"|"off"|"optional";
export type ReadinessItem={id:string;title:string;detail:string;state:ReadinessState;href?:string};
export type ReadinessSection={id:string;title:string;description:string;items:ReadinessItem[]};
export type ProjectReadiness={sections:ReadinessSection[];ready:number;required:number;attention:number};

const templateUses=[["role_acceptance","Role-acceptance email"],["role_group_welcome","Google / Propared welcome email"],["profile_access","Secure profile-access email"],["publicity_reminder","Publicity reminder email"],["profile_verification_code","Intake verification-code email"]] as const;
function title(value:string){return value.replace(/_/g," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());}
function complete(value:unknown){return Boolean(String(value??"").trim());}

export async function loadProjectReadiness(projectId:string,roleGroups:string[],guestArtistCount:number):Promise<ProjectReadiness>{
  const supabase=await createSupabaseServerClient();
  const [{data:groupSettings},{data:acceptance},{data:publicity},{data:templates},{data:playbillLink}]=await Promise.all([
    supabase.from("project_role_group_google_settings").select("role_group,active_google_group_email,google_group_sync_enabled,welcome_email_enabled,welcome_email_template_id,role_acceptance_email_template_id,propared_role_group_link").eq("project_id",projectId),
    supabase.from("project_role_acceptance_settings").select("auto_send,rehearsal_schedule,tech_schedule,performance_schedule").eq("project_id",projectId).maybeSingle(),
    supabase.from("project_publicity_settings").select("bio_due_on,headshot_due_on,reminders_enabled,bio_character_limit").eq("project_id",projectId).maybeSingle(),
    supabase.from("email_templates").select("id,project_id,name,usage_tags,active,updated_at").or(`project_id.eq.${projectId},project_id.is.null`).eq("active",true).order("updated_at",{ascending:false}),
    supabase.from("external_links").select("id").eq("local_entity_type","project").eq("local_entity_id",projectId).eq("external_app","playbill").eq("external_schema","app_playbill").eq("external_table","shows").maybeSingle()
  ]);
  const templateRows=templates??[];
  const activeFor=(tag:string)=>templateRows.find((row)=>row.project_id===projectId&&row.usage_tags?.includes(tag))??templateRows.find((row)=>!row.project_id&&row.usage_tags?.includes(tag));
  const deliveryReady=!DISABLE_OUTBOUND_EMAIL&&Boolean(process.env.RESEND_API_KEY?.trim())&&Boolean(process.env.EMAIL_FROM?.trim());
  const emailItems:ReadinessItem[]=[{id:"outbound-email",title:"Outbound email delivery",state:deliveryReady?"ready":"attention",detail:deliveryReady?`Enabled · sending as ${process.env.EMAIL_FROM}`:"Email delivery is disabled or Resend credentials are incomplete in the application environment."},...templateUses.map(([tag,label])=>{const found=activeFor(tag);return {id:`template-${tag}`,title:label,state:found?"ready" as const:"attention" as const,detail:found?`Default available: ${found.name}`:"No active project or all-productions template is available.",href:`/settings/email-templates?tag=${tag}`};})];
  const acceptanceItems:ReadinessItem[]=[
    {id:"acceptance-settings",title:"Student role-acceptance automation",state:acceptance?.auto_send?"ready":acceptance?"off":"attention",detail:acceptance?acceptance.auto_send?"Automatic sending is enabled when a student is offered a role.":"Configured, but automatic sending is turned off.":"Project acceptance settings have not been saved.",href:`/projects/${projectId}/onboarding`},
    {id:"acceptance-schedule",title:"Agreement schedule",state:acceptance&&complete(acceptance.rehearsal_schedule)&&complete(acceptance.tech_schedule)&&complete(acceptance.performance_schedule)?"ready":"attention",detail:acceptance&&complete(acceptance.rehearsal_schedule)&&complete(acceptance.tech_schedule)&&complete(acceptance.performance_schedule)?"Rehearsal, tech/dress, and performance/strike schedules are set.":"One or more required schedule sections are empty.",href:`/projects/${projectId}/onboarding`}
  ];
  const settingsByGroup=new Map((groupSettings??[]).map((row)=>[String(row.role_group),row]));const fallbackAcceptance=activeFor("role_acceptance");
  const groupItems:ReadinessItem[]=roleGroups.length?roleGroups.map((group)=>{const row=settingsByGroup.get(group);const missing:string[]=[];const off:string[]=[];if(!row)missing.push("group settings");else{if(!complete(row.active_google_group_email))missing.push("Google Group address");if(!row.google_group_sync_enabled)off.push("membership checks");if(!row.welcome_email_template_id||!templateRows.some((template)=>template.id===row.welcome_email_template_id&&template.usage_tags?.includes("role_group_welcome")))missing.push("active welcome template");if(!row.welcome_email_enabled)off.push("automatic welcome");if(!complete(row.propared_role_group_link))missing.push("Propared link");if(row.role_acceptance_email_template_id&&!templateRows.some((template)=>template.id===row.role_acceptance_email_template_id&&template.usage_tags?.includes("role_acceptance")))missing.push("active role-acceptance template");else if(!row.role_acceptance_email_template_id&&!fallbackAcceptance)missing.push("role-acceptance template");}const state:ReadinessState=missing.length?"attention":off.length?"off":"ready";const detail=missing.length?`Missing: ${missing.join(", ")}.`:off.length?`Configured, but off: ${off.join(", ")}.`:`Google address, membership check, role acceptance, welcome email, and Propared link are configured.`;return {id:`group-${group}`,title:title(group),state,detail,href:`/projects/${projectId}/google-groups?group=${encodeURIComponent(group)}#group-${group}`};}):[{id:"role-groups",title:"Project role groups",state:"attention",detail:"Create project roles before configuring group automation.",href:`/projects/${projectId}/roles`}];
  const integrationItems:ReadinessItem[]=[
    {id:"google-provider",title:"Google membership-check service",state:ENABLE_GOOGLE_GROUP_MEMBERSHIP_CHECK?"ready":"attention",detail:ENABLE_GOOGLE_GROUP_MEMBERSHIP_CHECK?"Apps Script membership checking is enabled.":"The application-level Google membership check is disabled.",href:`/projects/${projectId}/google-groups`},
    {id:"playbill",title:"Playbill integration",state:!ENABLE_PLAYBILL_WRITES?"off":playbillLink?"ready":"attention",detail:!ENABLE_PLAYBILL_WRITES?"Playbill writes are disabled in the application environment.":playbillLink?"Playbill writes are enabled and this project is linked to a show.":"Playbill writes are enabled, but this project is not linked to a show.",href:`/projects/${projectId}/integrations`},
    {id:"publicity",title:"Publicity deadlines and reminders",state:publicity&&complete(publicity.bio_due_on)&&complete(publicity.headshot_due_on)&&publicity.reminders_enabled?"ready":publicity&&!publicity.reminders_enabled?"off":"attention",detail:publicity?`${complete(publicity.bio_due_on)&&complete(publicity.headshot_due_on)?"Bio and headshot due dates are set":"One or both due dates are missing"} · reminders ${publicity.reminders_enabled?"on":"off"} · ${publicity.bio_character_limit??350} character limit.`:"Publicity settings have not been saved.",href:`/projects/${projectId}/publicity`},
    {id:"budget",title:"Theatre Budget integration",state:guestArtistCount?ENABLE_BUDGET_WRITES?"ready":"off":"optional",detail:guestArtistCount?ENABLE_BUDGET_WRITES?`${guestArtistCount} guest-artist assignment${guestArtistCount===1?"":"s"}; Budget writes are enabled.`:"Guest artists are assigned, but Budget writes are disabled.":"No guest artists are currently assigned; Budget setup is not required yet.",href:`/projects/${projectId}/integrations`}
  ];
  const sections:ReadinessSection[]=[{id:"email",title:"Email delivery and defaults",description:"Application delivery plus the templates used by automated messages.",items:emailItems},{id:"acceptance",title:"Student onboarding",description:"Role acceptance and the dates students agree to attend.",items:acceptanceItems},{id:"groups",title:"Role-group automation",description:"Every project role group must point to its Google, email, and Propared settings.",items:groupItems},{id:"integrations",title:"Integrations and publicity",description:"Project-level services that receive people, roles, bios, and headshots.",items:integrationItems}];
  const requiredItems=sections.flatMap((section)=>section.items).filter((item)=>item.state!=="optional");
  return {sections,ready:requiredItems.filter((item)=>item.state==="ready").length,required:requiredItems.length,attention:requiredItems.filter((item)=>item.state!=="ready").length};
}
