import { notFound } from "next/navigation";
import { submitRoleAcceptanceAction } from "@/app/role-acceptance/[token]/actions";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";
import { sanitizeRichText } from "@/lib/rich-text";

export const dynamic="force-dynamic";
type Section={key:string;title:string;body:string;acknowledgement:string;requires_response:boolean};
export default async function RoleAcceptancePage({params,searchParams}:{params:Promise<{token:string}>;searchParams?:Promise<{error?:string;submitted?:string;warning?:string}>}){
  const {token}=await params;const query=await searchParams;const admin=createSupabaseAdminClient();const {data:req}=await admin.from("role_acceptance_requests").select("*,people(full_name,preferred_name,email,pronouns),projects(title),role_assignments(project_roles(name,role_group))").eq("public_token",token).maybeSingle();if(!req)notFound();
  if(req.status==="sent")await admin.from("role_acceptance_requests").update({status:"opened",opened_at:new Date().toISOString()}).eq("id",req.id);
  const snapshot=req.template_snapshot as {name:string;type:string;version:number;introduction:string;sections:Section[];credit_options:string[];project_title:string;role_name:string;schedule?:{rehearsals?:string;tech_and_dress?:string;performances_and_strike?:string}};const person=req.people as unknown as {full_name:string;preferred_name:string;email:string;pronouns:string}|null;
  if(query?.submitted==="true"||["accepted","declined"].includes(req.status))return <div className="page public-form-page"><section className="panel"><p className="eyebrow">{snapshot.project_title}</p><h1>{req.status==="declined"?"Response recorded":"Role accepted"}</h1><p>{req.status==="declined"?"The production manager has been notified of your decision.":"Thank you. Production onboarding has begun. Watch for your Propared welcome message and instructions for completing your public profile, headshot, and show biography."}</p>{query?.warning?<p className="setup-warning">Your acceptance was saved. Staff will resolve this onboarding item: {query.warning}</p>:null}</section></div>;
  const requiredSections=snapshot.sections.filter((section)=>section.requires_response);
  return <div className="page public-form-page"><header className="page-header"><div><p className="eyebrow">{snapshot.project_title}</p><h1>{snapshot.name}</h1><p className="muted">Role: {snapshot.role_name} · Agreement version {snapshot.version}</p></div></header>{query?.error?<p className="setup-warning">{query.error}</p>:null}<section className="panel"><div className="rich-render" dangerouslySetInnerHTML={{__html:sanitizeRichText(snapshot.introduction)}}/><p><strong>{person?.preferred_name||person?.full_name}</strong><br/>{person?.email}{person?.pronouns?` · ${person.pronouns}`:""}</p></section>
    <form action={submitRoleAcceptanceAction} className="stacked-form"><input type="hidden" name="token" value={token}/><input type="hidden" name="requestId" value={req.id}/><input type="hidden" name="sectionKeys" value={JSON.stringify(requiredSections.map((section)=>section.key))}/>
      {snapshot.schedule&&Object.values(snapshot.schedule).some(Boolean)?<section className="panel agreement-section"><p className="eyebrow">Project Schedule</p><h2>Required production dates</h2><p className="muted">The schedule below is part of this role agreement. List any conflicts in the space provided before accepting.</p>{snapshot.schedule.rehearsals?<div className="schedule-block"><h3>Rehearsals</h3><p>{snapshot.schedule.rehearsals}</p></div>:null}{snapshot.schedule.tech_and_dress?<div className="schedule-block"><h3>Tech and dress</h3><p>{snapshot.schedule.tech_and_dress}</p></div>:null}{snapshot.schedule.performances_and_strike?<div className="schedule-block"><h3>Performances and strike</h3><p>{snapshot.schedule.performances_and_strike}</p></div>:null}</section>:null}
      {snapshot.sections.map((section)=><section className="panel agreement-section" key={section.key}><h2>{section.title}</h2><div className="agreement-copy rich-render" dangerouslySetInnerHTML={{__html:sanitizeRichText(section.body)}}/>{section.requires_response?<label className="checkbox-card"><input type="checkbox" name={`ack_${section.key}`}/><span className="rich-render" dangerouslySetInnerHTML={{__html:sanitizeRichText(section.acknowledgement)}}/></label>:null}</section>)}
      {snapshot.type==="cast"?<section className="panel"><h2>Schedule, safety, and questions</h2><label className="field"><span>List all conflicts (class schedule, work, and other commitments)</span><textarea name="conflicts" rows={5}/></label><label className="field"><span>Allergies production staff should know about</span><textarea name="allergies" rows={3}/><small>This is restricted project-specific information and is not added to your reusable public profile.</small></label></section>:null}
      <section className="panel"><h2>Role acceptance</h2><label className="field"><span>Production credits *</span><select name="creditChoice" required defaultValue=""><option value="">Choose one</option>{snapshot.credit_options.map((option)=><option value={option} key={option}>{option}</option>)}</select></label><label className="field"><span>Decision *</span><select name="decision" required defaultValue="accept"><option value="accept">I accept this role and agree to the requirements above</option><option value="decline">I decline this role</option></select></label><label className="field"><span>Type your full name to attest to this response *</span><input name="typedName" required/></label><label className="field"><span>Questions or comments</span><textarea name="comments" rows={4}/></label><button type="submit">Submit role acceptance</button></section>
    </form></div>;
}
