import Link from "next/link";
import { createEmailTemplateAction,updateEmailTemplateAction } from "@/app/settings/email-templates/actions";
import { HtmlMessageEditor } from "@/components/html-message-editor";
import { requireUser } from "@/lib/auth";
import { emailTemplateTagLabels,emailTemplateTags,emailTemplateVariables,type EmailTemplateTag } from "@/lib/email-template-catalog";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export const dynamic="force-dynamic";
type Template={id:string;project_id:string|null;template_type:string;usage_tags:string[];name:string;description:string;subject_template:string;body_template:string;active:boolean;projects:{title:string}|null};
function TagFields({template}:{template?:Template}){return <><label className="field"><span>Primary use</span><select name="primaryType" defaultValue={template?.template_type??"custom"}>{emailTemplateTags.map((tag)=><option key={tag} value={tag}>{emailTemplateTagLabels[tag]}</option>)}</select></label><fieldset><legend>Available in these parts of the app</legend><div className="choice-grid">{emailTemplateTags.map((tag)=><label className="checkbox-card" key={tag}><input type="checkbox" name="usageTags" value={tag} defaultChecked={template?.usage_tags?.includes(tag)??tag==="custom"}/><span>{emailTemplateTagLabels[tag]}</span></label>)}</div></fieldset></>}
function Scope({projects,template}:{projects:Array<{id:string;title:string}>;template?:Template}){return <label className="field"><span>Availability</span><select name="projectId" defaultValue={template?.project_id??""}><option value="">All productions</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.title} only</option>)}</select></label>}
export default async function EmailTemplatesPage({searchParams}:{searchParams?:Promise<{tag?:string;error?:string;success?:string}>}){
  await requireUser();const query=await searchParams;const supabase=await createSupabaseServerClient();const [{data:rows},{data:projects}]=await Promise.all([supabase.from("email_templates").select("id,project_id,template_type,usage_tags,name,description,subject_template,body_template,active,projects(title)").order("name"),supabase.from("projects").select("id,title").order("title")]);const selected=emailTemplateTags.includes(query?.tag as EmailTemplateTag)?query?.tag as EmailTemplateTag:null;const templates=((rows??[]) as unknown as Template[]).filter((template)=>!selected||template.usage_tags?.includes(selected));const projectRows=projects??[];
  return <div className="page workspace-page"><div className="page-header"><div><p className="eyebrow">Settings</p><h1>Email Templates</h1><p className="muted">Build each message once, tag where it belongs, and reuse it across Production Management.</p></div><Link className="button secondary" href="/settings/intake">Intake Forms</Link></div>{query?.error?<p className="setup-warning">{query.error}</p>:null}{query?.success?<p className="setup-success">{query.success}</p>:null}
    <nav className="workspace-nav" aria-label="Email template filters"><Link className={!selected?"active":""} href="/settings/email-templates">All</Link>{emailTemplateTags.map((tag)=><Link className={selected===tag?"active":""} key={tag} href={`/settings/email-templates?tag=${tag}`}>{emailTemplateTagLabels[tag]}</Link>)}</nav>
    <section className="panel"><details className="integration-panel"><summary><strong>Create email template</strong><span>Visual editor, optional source mode, tags, variables, and project scope</span></summary><form action={createEmailTemplateAction} className="stacked-form"><div className="form-row"><label className="field"><span>Template name</span><input name="name" required/></label><Scope projects={projectRows}/></div><label className="field"><span>Description</span><input name="description" placeholder="When should staff use this template?"/></label><TagFields/><label className="field"><span>Subject</span><input name="subject" defaultValue="A message about {{project_title}}" required/></label><HtmlMessageEditor name="bodyHtml" label="Email body" initialValue="<h3>Hello {{person_name}},</h3><p></p>"/><label className="checkbox-card"><input type="checkbox" name="active" defaultChecked/><span>Active and available in tagged workflows</span></label><button type="submit">Create email template</button></form></details></section>
    <section className="panel workspace-section"><div className="section-heading"><div><p className="eyebrow">Template Library</p><h2>{selected?emailTemplateTagLabels[selected]:"All email templates"}</h2><p className="muted">{templates.length} template{templates.length===1?"":"s"}. Project templates override general templates when a workflow chooses the newest active match.</p></div></div><div className="stacked-form">{templates.map((template)=><details className="integration-panel" key={template.id}><summary><strong>{template.name}</strong><span>{template.projects?.title??"All productions"} · {template.active?"Active":"Inactive"} · {template.usage_tags.map((tag)=>emailTemplateTagLabels[tag as EmailTemplateTag]??tag).join(", ")}</span></summary><form action={updateEmailTemplateAction} className="stacked-form"><input type="hidden" name="id" value={template.id}/><div className="form-row"><label className="field"><span>Template name</span><input name="name" defaultValue={template.name} required/></label><Scope projects={projectRows} template={template}/></div><label className="field"><span>Description</span><input name="description" defaultValue={template.description}/></label><TagFields template={template}/><label className="field"><span>Subject</span><input name="subject" defaultValue={template.subject_template} required/></label><HtmlMessageEditor name="bodyHtml" label="Email body" initialValue={template.body_template}/><p className="muted">Available variables for selected uses: {[...new Set(template.usage_tags.flatMap((tag)=>emailTemplateVariables[tag as EmailTemplateTag]??[]))].map((variable)=>`{{${variable}}}`).join(", ")||"No variables defined"}</p><label className="checkbox-card"><input type="checkbox" name="active" defaultChecked={template.active}/><span>Active and available in tagged workflows</span></label><button type="submit">Save template</button></form></details>)}</div></section>
  </div>;
}
