import Link from "next/link";
import { createEmailTemplateAction,updateEmailTemplateAction } from "@/app/settings/email-templates/actions";
import { HtmlMessageEditor } from "@/components/html-message-editor";
import { EmailTemplatePreviewDrawer } from "@/components/email-template-preview-drawer";
import { requireUser } from "@/lib/auth";
import { SITE_URL } from "@/lib/config";
import { emailTemplateTagLabels,emailTemplateTags,emailTemplateVariables,type EmailTemplateTag } from "@/lib/email-template-catalog";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export const dynamic="force-dynamic";
type Template={id:string;project_id:string|null;template_type:string;usage_tags:string[];name:string;description:string;subject_template:string;body_template:string;active:boolean;projects:{title:string}|null};
type GroupSetting={project_id:string;role_group:string;welcome_email_template_id:string|null;welcome_email_enabled:boolean;active_google_group_email:string;propared_role_group_link:string;projects:{title:string}|null};
type Automation={tone:"automatic"|"conditional"|"manual";label:string;summary:string;details:string[]};
function automation(template:Template,projects:Array<{id:string;title:string}>,groups:GroupSetting[],acceptance:Map<string,boolean>,publicity:Map<string,boolean>):Automation{const tags=template.usage_tags??[];if(tags.includes("role_group_welcome")){const linked=groups.filter((row)=>row.welcome_email_template_id===template.id),enabled=linked.filter((row)=>row.welcome_email_enabled);return enabled.length?{tone:"automatic",label:`Automatic in ${enabled.length} group${enabled.length===1?"":"s"}`,summary:"Sends when onboarding reaches the welcome step for enabled role groups.",details:linked.map((row)=>`${row.projects?.title??"Project"} · ${row.role_group.replace(/_/g," ")} · ${row.welcome_email_enabled?"automatic on":"off"}`)}:linked.length?{tone:"conditional",label:"Configured, sending off",summary:"Selected by project role groups, but welcome-email automation is disabled.",details:linked.map((row)=>`${row.projects?.title??"Project"} · ${row.role_group.replace(/_/g," ")} · off`)}:{tone:"conditional",label:"Not assigned",summary:"Available as a welcome template but not selected by a project role group.",details:[]};}if(tags.includes("role_acceptance")){const scoped=template.project_id?projects.filter((project)=>project.id===template.project_id):projects;const on=scoped.filter((project)=>acceptance.get(project.id)!==false),off=scoped.filter((project)=>acceptance.get(project.id)===false);return {tone:on.length?"automatic":"conditional",label:on.length?`Automatic in ${on.length} project${on.length===1?"":"s"}`:"Automatic sending off",summary:"Triggered when a student is assigned, subject to each project’s Onboarding setting.",details:[...on.map((project)=>`${project.title} · automatic on`),...off.map((project)=>`${project.title} · off`)]};}if(tags.includes("profile_access"))return {tone:"automatic",label:"Event-triggered",summary:"Sends when staff or a participant requests a secure profile link.",details:[]};if(tags.includes("profile_verification_code"))return {tone:"automatic",label:"Event-triggered",summary:"Sends when an existing person requests a verification code on an intake form.",details:[]};if(tags.includes("publicity_reminder")||tags.includes("profile_update_reminder")||tags.includes("submission_reminder")){const enabled=projects.filter((project)=>publicity.get(project.id)!==false);return {tone:"manual",label:"Manual reminder",summary:"Available from the Publicity dashboard. No background scheduler sends it automatically.",details:enabled.map((project)=>`${project.title} · reminders allowed`)};}return {tone:"manual",label:"Manual campaign",summary:"Used only when staff selects it while composing and explicitly sends a reviewed campaign.",details:[]};}
function TagFields({template}:{template?:Template}){return <><label className="field"><span>Primary use</span><select name="primaryType" defaultValue={template?.template_type??"custom"}>{emailTemplateTags.map((tag)=><option key={tag} value={tag}>{emailTemplateTagLabels[tag]}</option>)}</select></label><fieldset><legend>Available in these parts of the app</legend><div className="choice-grid">{emailTemplateTags.map((tag)=><label className="checkbox-card" key={tag}><input type="checkbox" name="usageTags" value={tag} defaultChecked={template?.usage_tags?.includes(tag)??tag==="custom"}/><span>{emailTemplateTagLabels[tag]}</span></label>)}</div></fieldset></>}
function Scope({projects,template}:{projects:Array<{id:string;title:string}>;template?:Template}){return <label className="field"><span>Availability</span><select name="projectId" defaultValue={template?.project_id??""}><option value="">All productions</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.title} only</option>)}</select></label>}
function dateLabel(value:string|null|undefined){return value?new Date(`${value}T00:00:00Z`).toLocaleDateString("en-US",{timeZone:"UTC",month:"short",day:"numeric",year:"numeric"}):"Not set";}
export default async function EmailTemplatesPage({searchParams}:{searchParams?:Promise<{tag?:string;error?:string;success?:string}>}){
  await requireUser();const query=await searchParams;const supabase=await createSupabaseServerClient();const [{data:rows},{data:projects},{data:groupSettings},{data:acceptanceSettings},{data:publicitySettings}]=await Promise.all([supabase.from("email_templates").select("id,project_id,template_type,usage_tags,name,description,subject_template,body_template,active,projects(title)").order("name"),supabase.from("projects").select("id,title").order("title"),supabase.from("project_role_group_google_settings").select("project_id,role_group,welcome_email_template_id,welcome_email_enabled,active_google_group_email,propared_role_group_link,projects(title)"),supabase.from("project_role_acceptance_settings").select("project_id,auto_send"),supabase.from("project_publicity_settings").select("project_id,bio_due_on,headshot_due_on,reminders_enabled")]);const selected=emailTemplateTags.includes(query?.tag as EmailTemplateTag)?query?.tag as EmailTemplateTag:null;const allTemplates=(rows??[]) as unknown as Template[];const templates=allTemplates.filter((template)=>!selected||template.usage_tags?.includes(selected));const projectRows=(projects??[]) as Array<{id:string;title:string}>;const groups=(groupSettings??[]) as unknown as GroupSetting[];const acceptance=new Map((acceptanceSettings??[]).map((row)=>[row.project_id,row.auto_send]));const publicity=new Map((publicitySettings??[]).map((row)=>[row.project_id,row.reminders_enabled]));const publicityDates=new Map((publicitySettings??[]).map((row)=>[row.project_id,row]));
  const previewProjects=projectRows.map((project)=>({id:project.id,title:project.title,bioDue:dateLabel(publicityDates.get(project.id)?.bio_due_on),headshotDue:dateLabel(publicityDates.get(project.id)?.headshot_due_on)}));const previewGroups=groups.map((group)=>({projectId:group.project_id,roleGroup:group.role_group,email:group.active_google_group_email??"",proparedLink:group.propared_role_group_link??""}));
  return <div className="page workspace-page"><div className="page-header"><div><p className="eyebrow">Settings</p><h1>Email Templates</h1><p className="muted">Build each message once, tag where it belongs, and reuse it across Production Management.</p></div><div className="top-actions"><EmailTemplatePreviewDrawer templates={allTemplates.filter((template)=>template.active)} projects={previewProjects} groups={previewGroups} siteUrl={SITE_URL}/><Link className="button secondary" href="/settings/intake">Intake Forms</Link></div></div>{query?.error?<p className="setup-warning">{query.error}</p>:null}{query?.success?<p className="setup-success">{query.success}</p>:null}
    <nav className="workspace-nav" aria-label="Email template filters"><Link className={!selected?"active":""} href="/settings/email-templates">All</Link>{emailTemplateTags.map((tag)=><Link className={selected===tag?"active":""} key={tag} href={`/settings/email-templates?tag=${tag}`}>{emailTemplateTagLabels[tag]}</Link>)}</nav>
    <section className="panel"><details className="integration-panel"><summary><strong>Create email template</strong><span>Visual editor, optional source mode, tags, variables, and project scope</span></summary><form action={createEmailTemplateAction} className="stacked-form"><div className="form-row"><label className="field"><span>Template name</span><input name="name" required/></label><Scope projects={projectRows}/></div><label className="field"><span>Description</span><input name="description" placeholder="When should staff use this template?"/></label><TagFields/><label className="field"><span>Subject</span><input name="subject" defaultValue="A message about {{project_title}}" required/></label><HtmlMessageEditor name="bodyHtml" label="Email body" initialValue="<h3>Hello {{person_name}},</h3><p></p>"/><label className="checkbox-card"><input type="checkbox" name="active" defaultChecked/><span>Active and available in tagged workflows</span></label><button type="submit">Create email template</button></form></details></section>
    <section className="panel workspace-section"><div className="section-heading"><div><p className="eyebrow">Template Library</p><h2>{selected?emailTemplateTagLabels[selected]:"All email templates"}</h2><p className="muted">{templates.length} template{templates.length===1?"":"s"}. Project templates override general templates when a workflow chooses the newest active match.</p></div></div><div className="stacked-form">{templates.map((template)=>{const status=automation(template,projectRows,groups,acceptance,publicity);return <details className="integration-panel" key={template.id}><summary><strong>{template.name}</strong><span>{template.projects?.title??"All productions"} · {template.active?"Active":"Inactive"} · {template.usage_tags.map((tag)=>emailTemplateTagLabels[tag as EmailTemplateTag]??tag).join(", ")} · <span className={`automation-badge ${status.tone}`}>{template.active?status.label:"Inactive"}</span></span></summary><form action={updateEmailTemplateAction} className="stacked-form"><input type="hidden" name="id" value={template.id}/><div className={`template-automation ${template.active?status.tone:"conditional"}`}><strong>{template.active?status.label:"Inactive — never selected by workflows"}</strong><p>{template.active?status.summary:"This template remains saved but cannot be sent by an automatic or manual workflow until it is activated."}</p>{template.active&&status.details.length?<ul>{status.details.map((detail)=><li key={detail}>{detail}</li>)}</ul>:null}</div><div className="form-row"><label className="field"><span>Template name</span><input name="name" defaultValue={template.name} required/></label><Scope projects={projectRows} template={template}/></div><label className="field"><span>Description</span><input name="description" defaultValue={template.description}/></label><TagFields template={template}/><label className="field"><span>Subject</span><input name="subject" defaultValue={template.subject_template} required/></label><HtmlMessageEditor name="bodyHtml" label="Email body" initialValue={template.body_template}/><p className="muted">Available variables for selected uses: {[...new Set(template.usage_tags.flatMap((tag)=>emailTemplateVariables[tag as EmailTemplateTag]??[]))].map((variable)=>`{{${variable}}}`).join(", ")||"No variables defined"}</p><label className="checkbox-card"><input type="checkbox" name="active" defaultChecked={template.active}/><span>Active and available in tagged workflows</span></label><button type="submit">Save template</button></form></details>;})}</div></section>
  </div>;
}
