import { notFound } from "next/navigation";
import { requestIntakeVerificationCodeAction, verifyIntakeCodeAction } from "@/app/intake/actions";
import { submitTechnicalInterestAction } from "@/app/interest/[token]/actions";
import { getVerifiedProfile } from "@/lib/profile-intake";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";

export const dynamic = "force-dynamic";

export default async function TechnicalInterestPage({ params, searchParams }: { params: Promise<{token:string}>; searchParams?: Promise<{challenge?:string;profile?:string;error?:string;success?:string;notice?:string;submitted?:string}> }) {
  const { token } = await params; const query = await searchParams; const admin = createSupabaseAdminClient();
  const { data: form } = await admin.from("technical_interest_forms").select("*").eq("public_token", token).eq("status", "published").maybeSingle();
  if (!form) notFound();
  if (query?.submitted === "true") return <div className="page public-form-page"><section className="panel"><p className="eyebrow">Siena Theatre</p><h1>Thank you</h1><p>Your interests and reusable production profile have been saved. You can submit this form again later if your interests or experience change.</p></section></div>;
  const profile = await getVerifiedProfile(query?.profile, "technical_interest", String(form.id));
  return <div className="page public-form-page"><header className="page-header"><div><p className="eyebrow">Siena Theatre</p><h1>{form.title}</h1><p className="muted">{form.description}</p></div></header>
    {query?.error?<p className="setup-warning">{query.error}</p>:null}{query?.success?<p className="setup-success">{query.success}</p>:null}{query?.notice?<p className="setup-success">{query.notice}</p>:null}
    <section className="panel"><h2>Already have a profile?</h2><p className="muted">Enter the email saved on your profile and your exact 90# when applicable. We will email a six-digit code before showing saved details.</p>
      <form action={requestIntakeVerificationCodeAction} className="form-row"><input type="hidden" name="contextType" value="technical_interest"/><input type="hidden" name="contextId" value={form.id}/><input type="hidden" name="contextToken" value={token}/><label className="field"><span>Email</span><input type="email" name="email" required/></label><label className="field"><span>90# (if applicable)</span><input name="vendorNumber"/></label><button type="submit">Load my saved profile</button></form>
      {query?.challenge?<form action={verifyIntakeCodeAction} className="form-row"><input type="hidden" name="contextType" value="technical_interest"/><input type="hidden" name="contextId" value={form.id}/><input type="hidden" name="contextToken" value={token}/><input type="hidden" name="challengeId" value={query.challenge}/><label className="field"><span>Six-digit verification code</span><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></label><button type="submit">Verify and add details</button></form>:null}
    </section>
    <form action={submitTechnicalInterestAction} className="stacked-form"><input type="hidden" name="formToken" value={token}/><input type="hidden" name="formId" value={form.id}/><input type="hidden" name="profileSession" value={query?.profile??""}/>
      <section className="panel"><h2>Contact and profile</h2><div className="form-row"><label className="field"><span>Full name *</span><input name="fullName" defaultValue={profile?.full_name??""} required/></label><label className="field"><span>Preferred name</span><input name="preferredName" defaultValue={profile?.preferred_name??""}/></label></div><div className="form-row"><label className="field"><span>Email *</span><input type="email" name="email" defaultValue={profile?.email??""} readOnly={Boolean(profile)} required/></label><label className="field"><span>90#</span><input name="vendorNumber" defaultValue={profile?.vendor_number??""} readOnly={Boolean(profile)}/></label></div><div className="form-row"><label className="field"><span>Phone</span><input name="phone" defaultValue={profile?.phone??""}/></label><label className="field"><span>Pronouns</span><input name="pronouns" defaultValue={profile?.pronouns??""}/></label><label className="field"><span>Affiliation / graduation year</span><input name="affiliation" defaultValue={profile?.affiliation??""}/></label></div></section>
      <section className="panel"><h2>Technical and production interests</h2><div className="choice-grid">{(form.technical_options as string[]).map((option)=><label className="checkbox-card" key={option}><input type="checkbox" name="technicalInterests" value={option} defaultChecked={profile?.technical_interests.includes(option)}/><span>{option}</span></label>)}</div><label className="field"><span>Other technical interests</span><input name="otherTechnicalInterest"/></label><label className="field"><span>Technical experience</span><textarea name="technicalExperience" rows={5} defaultValue={profile?.technical_experience??""}/></label></section>
      <section className="panel"><h2>Performance, music, and movement</h2><label className="field"><span>Vocal range</span><select name="vocalRange" defaultValue={profile?.vocal_range??""}><option value="">Prefer not to answer</option>{(form.vocal_range_options as string[]).map((option)=><option value={option} key={option}>{option}</option>)}</select></label><label className="field"><span>Other vocal range</span><input name="otherVocalRange"/></label><label className="field"><span>Instruments and proficiency</span><textarea name="instruments" rows={3} defaultValue={profile?.instruments??""}/></label><div className="choice-grid">{(form.dance_style_options as string[]).map((option)=><label className="checkbox-card" key={option}><input type="checkbox" name="danceStyles" value={option} defaultChecked={profile?.dance_styles.includes(option)}/><span>{option}</span></label>)}</div><label className="field"><span>Other dance styles</span><input name="otherDanceStyle"/></label><label className="field"><span>Dance and movement experience</span><textarea name="danceExperience" rows={3} defaultValue={profile?.dance_experience??""}/></label><label className="field"><span>Performance experience</span><textarea name="performanceExperience" rows={5} defaultValue={profile?.performance_experience??""}/></label></section>
      <section className="panel"><h2>Additional experience</h2><label className="field"><span>Special skills</span><textarea name="specialSkills" rows={4} defaultValue={profile?.special_skills??""}/></label><label className="field"><span>Certifications and training</span><textarea name="certificationsTraining" rows={4} defaultValue={profile?.certifications_training??""}/></label></section>
      <button type="submit">Save my profile and interests</button>
    </form>
  </div>;
}
