import Link from "next/link";
import { AgreementSectionsEditor, type AgreementSection } from "@/components/agreement-sections-editor";
import { HtmlMessageEditor } from "@/components/html-message-editor";
import { requireUser } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { saveAcceptanceTemplateAction, saveTechnicalInterestFormAction } from "@/app/settings/intake/actions";

export const dynamic="force-dynamic";
export default async function IntakeSettingsPage({searchParams}:{searchParams?:Promise<{error?:string;success?:string}>}){
  await requireUser(); const query=await searchParams; const supabase=await createSupabaseServerClient();
  const [{data:forms},{data:templates},{data:submissions}]=await Promise.all([supabase.from("technical_interest_forms").select("*").order("created_at").limit(1),supabase.from("role_acceptance_templates").select("*").eq("active",true).order("template_type"),supabase.from("technical_interest_submissions").select("id, submitted_at, people(full_name,email)").order("submitted_at",{ascending:false}).limit(20)]);
  const form=forms?.[0];
  return <div className="page workspace-page"><div className="page-header"><div><p className="eyebrow">Settings</p><h1>Intake and Acceptance</h1><p className="muted">Manage the evergreen Technical Theatre Interest form and the seeded cast and crew acceptance agreements.</p></div><Link className="button secondary" href="/settings/reference-data">Reference Data</Link></div>
    {query?.error?<p className="setup-warning">{query.error}</p>:null}{query?.success?<p className="setup-success">{query.success}</p>:null}
    {form?<section className="panel"><div className="section-heading"><div><p className="eyebrow">Evergreen Intake</p><h2>Technical Theatre Interest Form</h2></div><Link className="button secondary" target="_blank" href={`/interest/${form.public_token}`}>Open public form</Link></div><form action={saveTechnicalInterestFormAction} className="stacked-form"><input type="hidden" name="id" value={form.id}/><div className="form-row"><label className="field"><span>Title</span><input name="title" defaultValue={form.title}/></label><label className="field"><span>Status</span><select name="status" defaultValue={form.status}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><label className="field"><span>Description</span><textarea name="description" rows={4} defaultValue={form.description}/></label><div className="form-row"><label className="field"><span>Technical interests (one per line)</span><textarea name="technicalOptions" rows={12} defaultValue={(form.technical_options??[]).join("\n")}/></label><label className="field"><span>Vocal ranges (one per line)</span><textarea name="vocalRangeOptions" rows={12} defaultValue={(form.vocal_range_options??[]).join("\n")}/></label><label className="field"><span>Dance styles (one per line)</span><textarea name="danceStyleOptions" rows={12} defaultValue={(form.dance_style_options??[]).join("\n")}/></label></div><button type="submit">Save interest form</button></form></section>:null}
    <section className="panel workspace-section"><p className="eyebrow">Student Agreement Defaults</p><h2>Defaults for new projects</h2><p className="muted">These evergreen Cast and Crew templates seed new project agreements. Final wording, schedules, and credit choices belong to each project under Onboarding; changing a default does not replace a project’s saved customization.</p><div className="stacked-form">{(templates??[]).map((template)=><details className="integration-panel" key={template.id} open><summary><strong>{template.name}</strong><span>{template.template_type} default · version {template.version}</span></summary><form action={saveAcceptanceTemplateAction} className="stacked-form"><input type="hidden" name="id" value={template.id}/><label className="field"><span>Default name</span><input name="name" defaultValue={template.name}/></label><HtmlMessageEditor name="introduction" initialValue={template.introduction} label="Default introduction"/><AgreementSectionsEditor name="sections" label={`Default ${template.template_type} agreement sections`} initialSections={(template.sections??[]) as AgreementSection[]}/><label className="field"><span>Default credit choices (one per line)</span><textarea name="creditOptions" rows={6} defaultValue={(template.credit_options??[]).join("\n")}/></label><button type="submit">Save {template.template_type} defaults</button></form></details>)}</div></section>
    <section className="panel workspace-section"><p className="eyebrow">Recent Intake</p><h2>Technical Interest Submissions</h2><div className="compact-list">{(submissions??[]).map((row)=>{const person=row.people as unknown as {full_name:string;email:string}|null;return <div className="table-row" key={row.id}><div><strong>{person?.full_name??"Unknown person"}</strong><span>{person?.email??""} · {new Date(row.submitted_at).toLocaleString()}</span></div></div>})}</div></section>
  </div>;
}
